# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='poke_number',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='poke',
            name='user',
        ),
        migrations.AddField(
            model_name='poke',
            name='user',
            field=models.ManyToManyField(related_name='pokes', to='poke.User'),
        ),
    ]
